### GET request to example server
GET http://localhost:8080/todo

###
POST http://localhost:8080/todo

{
"item": "yes v"
}

### GET request to example server
GET http://localhost:8080/api/publications